/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Dialog;

import View.LoginAndForgetPassword.PasswordRevocerForm;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Admin
 */
public class WarningExitDialog extends javax.swing.JDialog {

    /**
     * Creates new form SuccessDialog
     */

    public boolean Accept = false;
    public WarningExitDialog() {
        initComponents();
    }

    public WarningExitDialog(String input) {  
        initComponents();   
        setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null);     
        InputNoti.setText(input);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InputNoti = new javax.swing.JLabel();
        NoButton = new javax.swing.JLabel();
        YesButton = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setModal(true);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        InputNoti.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        InputNoti.setForeground(new java.awt.Color(204, 204, 204));
        InputNoti.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(InputNoti, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 440, 60));

        NoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NoButtonMouseClicked(evt);
            }
        });
        getContentPane().add(NoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 330, 106, 35));

        YesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                YesButtonMouseClicked(evt);
            }
        });
        getContentPane().add(YesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 328, 168, 37));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/WarningExitDialog.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NoButtonMouseClicked
        // TODO add your handling code here:
        
        Accept = false;
        this.setVisible(false);
    }//GEN-LAST:event_NoButtonMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//        for (double i = 0.0; i <= 1; i += 0.1) {
//            String val = i + "";
//            float f = Float.valueOf(val);
//            this.setOpacity(f);
//            try {
//                Thread.sleep(50);
//            } catch (InterruptedException ex) {
//                Logger.getLogger(PasswordRevocerForm.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        }
    }//GEN-LAST:event_formWindowOpened

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.setVisible(false);
        }
    }//GEN-LAST:event_formKeyPressed

    private void YesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_YesButtonMouseClicked
        Accept = true;
        this.setVisible(false);
    }//GEN-LAST:event_YesButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WarningExitDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WarningExitDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WarningExitDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WarningExitDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WarningExitDialog("Noi dung").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel InputNoti;
    private javax.swing.JLabel NoButton;
    private javax.swing.JLabel YesButton;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
