/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Admin;

import Controller.ChiTietHoaDonCTR;
import Controller.HoaDonCTR;
import Controller.NhanVienCTR;
import Controller.TaiKhoanCTR;
import Object.NhanVien;
import Object.TaiKhoan;
import Processor.Encrypt;
import java.util.ArrayList;
import java.util.regex.Pattern;
//import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Processor.*;
import View.Dialog.ErrorDialog;
import View.Dialog.SuccessDialog;
import View.Dialog.WarningDialg;

/**
 *
 * @author Admin
 */
public class jPanelStaff extends javax.swing.JPanel {

    TaiKhoanCTR tkc = new TaiKhoanCTR();
    HoaDonCTR hdc = new HoaDonCTR();
    NhanVienCTR nvc = new NhanVienCTR();
    ChiTietHoaDonCTR cthdc = new ChiTietHoaDonCTR();
    ArrayList<Object[]> ltk = new ArrayList();
    DefaultTableModel Dtable;
    Boolean addable = true;
    Boolean delete = true;

    /**
     * Creates new form jPanelNhanVien1
     */
    public jPanelStaff() {
        initComponents();
        Dtable = (DefaultTableModel) tableNV.getModel();
        //txtTenDN.setEnabled(false);
        //txtPassword.setEnabled(false);
        showNV();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        tableNV = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnSuaNV = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnXoaNV = new javax.swing.JLabel();
        btnThemNV = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnClear = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        comboboxGioiTinh = new javax.swing.JComboBox<>();
        txtEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        txtTenNV = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTenDN = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        comboboxLoaiNV = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane4.setPreferredSize(new java.awt.Dimension(600, 500));

        tableNV.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        tableNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Staff ID", "Staff Name", "Email", "Address", "Phone", "Sex"
            }
        ));
        tableNV.setPreferredSize(new java.awt.Dimension(180, 615));
        tableNV.setShowGrid(false);
        tableNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableNVMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tableNV);
        if (tableNV.getColumnModel().getColumnCount() > 0) {
            tableNV.getColumnModel().getColumn(5).setMinWidth(0);
            tableNV.getColumnModel().getColumn(5).setMaxWidth(0);
        }

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnSuaNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/icons8_edit_file_48px.png"))); // NOI18N
        btnSuaNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuaNVMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel4.setText("Change Detail");

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel3.setText("Delete Staff");

        btnXoaNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/icons8_waste_48px.png"))); // NOI18N
        btnXoaNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaNVMouseClicked(evt);
            }
        });

        btnThemNV.setToolTipText("Thêm hội viên");
        btnThemNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/icons8_add_user_group_man_man_48px.png"))); // NOI18N
        btnThemNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemNVMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel2.setText("Add Staff");

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/icons8_broom_48px.png"))); // NOI18N
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel11.setText("Clear");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnThemNV, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(btnXoaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(btnSuaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel11)))
                .addGap(54, 54, 54))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSuaNV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThemNV, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(30, 30, 30))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comboboxGioiTinh.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        comboboxGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel3.add(comboboxGioiTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 219, -1));

        txtEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel3.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 219, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel6.setText("User  (*):");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel5.setText("Phone (*):");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 129, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel1.setText("Full Name (*):");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 52, -1, -1));

        txtDiaChi.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel3.add(txtDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 219, -1));

        txtTenNV.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel3.add(txtTenNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 219, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel8.setText("Address: ");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel9.setText("Sex:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 167, -1, -1));

        txtTenDN.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel3.add(txtTenDN, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 219, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel12.setText("Email: (*)");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 205, -1, -1));

        txtSDT.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel3.add(txtSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 219, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel13.setText("Account type: ");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 252, -1, -1));

        comboboxLoaiNV.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        comboboxLoaiNV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Staff" }));
        comboboxLoaiNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxLoaiNVActionPerformed(evt);
            }
        });
        jPanel3.add(comboboxLoaiNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 219, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnXoaNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaNVMouseClicked
        // TODO add your handling code here:
        //MaNV[0],TenNV[1], DiaChi[2], SDT[3], GioiTinh[4], Email[5], TenDangNhap[6], LoaiTK[7], [8]PassWord
        if (delete == true) {
            int index = tableNV.getSelectedRow();
            if (index == -1) {
                new ErrorDialog("Please choose staff first!").setVisible(true);
            } else if (ltk.isEmpty()) {
                new ErrorDialog("There are not any staff!").setVisible(true);
            } else if (Integer.parseInt(ltk.get(index)[7] + "") == 1) {
                new ErrorDialog("Can not delete admin account!").setVisible(true);
            } else {
                WarningDialg w = new WarningDialg("Are you sure to delete this staff and his(her) account?");
                w.setVisible(true);
                if (w.Accept == true) {
                    if (hdc.getData(Integer.parseInt(ltk.get(index)[0] + "")) == false) {
                        try {
                            if (tkc.DeleteData((String) ltk.get(index)[6])) {  // xóa tài khoản
                                nvc.DeleteData(Integer.parseInt(ltk.get(index)[0] + ""));// xóa nhân viên
                                new SuccessDialog("Delete successfully!").setVisible(true);
                                showNV();
                            }
                        } catch (Exception e) {
                        }
                    } else {
                        new ErrorDialog("Can not delete staff who had created bills!").setVisible(true);
                    }
                }
            }
        }
    }//GEN-LAST:event_btnXoaNVMouseClicked

    private void btnThemNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemNVMouseClicked
        //regex r = new regex();
        if (addable == true) {
            Boolean TenDangNhapCheck = true;
            Boolean PasswordCheck = true;
            Boolean SDTCheck = true;
            Boolean TenNVCheck = true;
            Boolean EmailCheck = true;
            Boolean DiaChiCheck = true;
            Boolean IsOK = true;
            String TenNV = txtTenNV.getText();//khong duoc rong
            String DiaChi = txtDiaChi.getText();
            String SDT = txtSDT.getText();
            String GioiTinh = comboboxGioiTinh.getSelectedItem().toString();
            String TenDN = txtTenDN.getText();
            String Email = txtEmail.getText();
            if (TenNV.isEmpty() || SDT.isEmpty() || TenNV.isEmpty() || Email.isEmpty()) {
                new ErrorDialog("Please fill all the fill with have (*)").setVisible(true);
                IsOK = false;
            } else {
                Pattern pattern = Pattern.compile(Regex.TenPattern);

                if (!pattern.matcher(txtTenNV.getText()).find()) {
                    IsOK = false;
                    TenNVCheck = false;
                }

                pattern = Pattern.compile(Regex.TenDangNhap_PasswordPattern);

                if (!pattern.matcher(txtTenDN.getText()).find()) {
                    IsOK = false;
                    TenDangNhapCheck = false;
                }
                pattern = Pattern.compile(Regex.TenDangNhap_PasswordPattern);
                if (!pattern.matcher(txtTenDN.getText()).find()) {
                    IsOK = false;
                    PasswordCheck = false;
                }
                pattern = Pattern.compile(Regex.SdtPattern);
                if (!pattern.matcher(txtSDT.getText()).find()) {
                    IsOK = false;
                    SDTCheck = false;
                }

                pattern = Pattern.compile(Regex.EmailPattern);
                if (!pattern.matcher(txtEmail.getText()).find()) {
                    IsOK = false;
                    EmailCheck = false;
                }
                if (!txtDiaChi.getText().equals("")) {
                    pattern = Pattern.compile(Regex.DiaChiPattern);
                    if (!pattern.matcher(txtDiaChi.getText()).find()) {
                        IsOK = false;
                        DiaChiCheck = false;
                    }
                }
                if (TenNVCheck == false || EmailCheck == false || SDTCheck == false || DiaChiCheck == false || PasswordCheck == false || TenDangNhapCheck == false) {
                    System.out.println(TenNVCheck);
                    System.out.println(EmailCheck);
                    System.out.println(SDTCheck);
                    System.out.println(DiaChiCheck);
                    System.out.println(PasswordCheck);
                    System.out.println(TenDangNhapCheck);
                    new ErrorDialog("Please type match the regex!").setVisible(true);
                }
            }
            if (IsOK) {
                Encrypt e = new Encrypt();
                String Password = e.encryptPassword("1");
                NhanVien nv = new NhanVien(0, TenNV, DiaChi, SDT, GioiTinh, Email);

                if (nvc.AddData(nv)) {
                    int LoaiTK = comboboxLoaiNV.getSelectedIndex() + 1;
                    TaiKhoan tk = new TaiKhoan(TenDN, Password, LoaiTK, nvc.getCurrentID());
                    if (tkc.AddData(tk)) {
                        new SuccessDialog("Add successfully with default password " + "1").setVisible(true);
                        showNV();

                    }
                } else {
                    new ErrorDialog("This email has been used to regist an other account!").setVisible(true);
                }

            }
        }
    }//GEN-LAST:event_btnThemNVMouseClicked

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        // TODO add your handling code here:
        addable = true;
        delete = true;
        btnThemNV.setEnabled(true);
        btnXoaNV.setEnabled(true);
        txtTenNV.setText("");
        txtDiaChi.setText("");
        txtEmail.setText("");
        txtTenDN.setText("");
        txtSDT.setText("");
        comboboxGioiTinh.setSelectedItem("Male");
        txtTenDN.setEnabled(true);
        comboboxLoaiNV.setEnabled(true);
    }//GEN-LAST:event_btnClearMouseClicked

    private void tableNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNVMouseClicked
        // TODO add your handling code here:
        //MaNV[0],TenNV[1], DiaChi[2], SDT[3], GioiTinh[4], Email[5], TenDangNhap[6], LoaiTK[7], [8]PassWord
        int index = tableNV.getSelectedRow();
        if (index != -1) {
            if (Integer.parseInt(ltk.get(index)[7] + "") == 2) {
                addable = false;
                delete = true;
                btnThemNV.setEnabled(false);
                btnXoaNV.setEnabled(true);
                txtTenDN.setEnabled(false);
                txtTenDN.setText((String) ltk.get(index)[6]);
                txtDiaChi.setText((String) ltk.get(index)[2]);
                txtTenNV.setText((String) ltk.get(index)[1]);
                txtSDT.setText((String) ltk.get(index)[3]);
                txtEmail.setText((String) ltk.get(index)[5]);
                comboboxGioiTinh.setEnabled(false);
                comboboxGioiTinh.setSelectedItem((String) ltk.get(index)[4]);
                comboboxLoaiNV.setEnabled(true);
                comboboxLoaiNV.setSelectedIndex(Integer.parseInt(ltk.get(index)[7] + "") - 1);
            } else {
                addable = false;
                delete = false;
                btnThemNV.setEnabled(false);
                btnXoaNV.setEnabled(false);
                txtTenDN.setEnabled(false);
                txtTenDN.setText((String) ltk.get(index)[6]);
                txtDiaChi.setText((String) ltk.get(index)[2]);
                txtTenNV.setText((String) ltk.get(index)[1]);
                txtSDT.setText((String) ltk.get(index)[3]);
                txtEmail.setText((String) ltk.get(index)[5]);
                comboboxGioiTinh.setEnabled(false);
                comboboxLoaiNV.setEnabled(false);
                comboboxLoaiNV.setSelectedIndex(Integer.parseInt(ltk.get(index)[7] + "") - 1);
                comboboxGioiTinh.setSelectedItem((String) ltk.get(index)[4]);
            }
        }

    }//GEN-LAST:event_tableNVMouseClicked

    private void btnSuaNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaNVMouseClicked
        // TODO add your handling code here:
        int index = tableNV.getSelectedRow();
        if (index == -1) {
            new ErrorDialog("PLease choose staff first!!").setVisible(true);
        } else if (ltk.isEmpty()) {
            new ErrorDialog("There are not any staff yet!").setVisible(true);
        } else {
            WarningDialg w = new WarningDialg("Are you sure to update info this staff?");
            w.setVisible(true);
            if (w.Accept == true) {
                Boolean TenDangNhapCheck = true;
                Boolean PasswordCheck = true;
                Boolean SDTCheck = true;
                Boolean TenNVCheck = true;
                Boolean EmailCheck = true;
                Boolean DiaChiCheck = true;
                Boolean IsOK = true;
                String TenNV = txtTenNV.getText();//khong duoc rong
                String DiaChi = txtDiaChi.getText();
                String SDT = txtSDT.getText();
                String GioiTinh = comboboxGioiTinh.getSelectedItem().toString();
                String TenDN = txtTenDN.getText();
                String Email = txtEmail.getText();
                if (TenNV.isEmpty() || SDT.isEmpty() || TenNV.isEmpty() || Email.isEmpty()) {
                    new ErrorDialog("Please fill all the field with have (*)!").setVisible(true);
                    IsOK = false;
                } else {
                    Pattern pattern = Pattern.compile(Regex.TenPattern);

                    if (!pattern.matcher(txtTenNV.getText()).find()) {
                        IsOK = false;
                        TenNVCheck = false;
                    }

                    pattern = Pattern.compile(Regex.TenDangNhap_PasswordPattern);

                    if (!pattern.matcher(txtTenDN.getText()).find()) {
                        IsOK = false;
                        TenDangNhapCheck = false;
                    }
                    pattern = Pattern.compile(Regex.TenDangNhap_PasswordPattern);
                    if (!pattern.matcher(txtTenDN.getText()).find()) {
                        IsOK = false;
                        PasswordCheck = false;
                    }

                    pattern = Pattern.compile(Regex.SdtPattern);
                    if (!pattern.matcher(txtSDT.getText()).find()) {
                        IsOK = false;
                        SDTCheck = false;
                    }
                    if (!txtDiaChi.getText().equals("")) {
                        pattern = Pattern.compile(Regex.DiaChiPattern);
                        if (!pattern.matcher(txtDiaChi.getText()).find()) {
                            IsOK = false;
                            DiaChiCheck = false;
                        }
                    }
                    pattern = Pattern.compile(Regex.EmailPattern);
                    if (!pattern.matcher(txtEmail.getText()).find()) {
                        IsOK = false;
                        EmailCheck = false;
                    }
                    if (!txtDiaChi.getText().equals("")) {
                        pattern = Pattern.compile(Regex.DiaChiPattern);
                        if (!pattern.matcher(txtDiaChi.getText()).find()) {
                            IsOK = false;
                            DiaChiCheck = false;
                        }
                    }
                    if (TenNVCheck == false || EmailCheck == false || SDTCheck == false || DiaChiCheck == false || PasswordCheck == false || TenDangNhapCheck == false) {
                        new ErrorDialog("Please type match the regex!").setVisible(true);
                    }
                }
                if (IsOK) {
                    Encrypt e = new Encrypt();
                    String Password = e.encryptPassword("1");
                    NhanVien nv = new NhanVien(nvc.GetMaNVByTenDangNhap(TenDN), TenNV, DiaChi, SDT, GioiTinh, Email);

                    if (nvc.UpdateData(nv)) {
                        int LoaiTK = comboboxLoaiNV.getSelectedIndex() + 1;
                        //System.out.println(LoaiTK);
                        TaiKhoan tk = new TaiKhoan(TenDN, Password, LoaiTK, nvc.getCurrentID());
                        if (tkc.UpdateData(tk)) {
                            new SuccessDialog("Update sucessfully!").setVisible(true);
                            showNV();
                        }
                    } else {
                        new ErrorDialog("This email has already used to regist an other account!").setVisible(true);
                    }

                }
            }
        }
    }//GEN-LAST:event_btnSuaNVMouseClicked

    private void comboboxLoaiNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxLoaiNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboboxLoaiNVActionPerformed

    public void showNV() {
        ltk = tkc.getDataJoinNVAndTaiKhoan();
        if (tableNV.getRowCount() > 0) {
            Dtable.setRowCount(0);
        }
        for (Object[] objects : ltk) {
            Dtable.addRow(new Object[]{objects[0], objects[1], objects[5], objects[2], objects[3]});
        }

        //tableNV.getModel().getValueAt(WIDTH, WIDTH)
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnClear;
    private javax.swing.JLabel btnSuaNV;
    private javax.swing.JLabel btnThemNV;
    private javax.swing.JLabel btnXoaNV;
    private javax.swing.JComboBox<String> comboboxGioiTinh;
    private javax.swing.JComboBox<String> comboboxLoaiNV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tableNV;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenDN;
    private javax.swing.JTextField txtTenNV;
    // End of variables declaration//GEN-END:variables
}
