/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Admin;

import Processor.ExelExport;
import java.awt.Color;

/**
 *
 * @author Admin
 */
public class jPanelExelExport extends javax.swing.JPanel {

    /**
     * Creates new form jPanelExelExport
     */
    ExelExport ee;
    public jPanelExelExport() {
        initComponents();
        ee = new ExelExport();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ExportCustomer = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnThemHV1 = new javax.swing.JLabel();
        ExportStaff = new javax.swing.JPanel();
        btnThemHV = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ExportPackage = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnThemHV5 = new javax.swing.JLabel();
        ExportVoucher = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnThemHV6 = new javax.swing.JLabel();
        ExportBill = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnThemHV2 = new javax.swing.JLabel();
        ExportDetailBill = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btnThemHV4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 102, 102));

        ExportCustomer.setBackground(new java.awt.Color(94, 91, 91));
        ExportCustomer.setPreferredSize(new java.awt.Dimension(120, 120));
        ExportCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExportCustomerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExportCustomerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExportCustomerMouseExited(evt);
            }
        });
        ExportCustomer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Export customer list");
        ExportCustomer.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 100, 30));

        btnThemHV1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/icons8_microsoft_excel_60px_1.png"))); // NOI18N
        ExportCustomer.add(btnThemHV1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 60, 70));

        ExportStaff.setBackground(new java.awt.Color(94, 91, 91));
        ExportStaff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExportStaffMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExportStaffMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExportStaffMouseExited(evt);
            }
        });
        ExportStaff.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnThemHV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/icons8_microsoft_excel_60px_1.png"))); // NOI18N
        ExportStaff.add(btnThemHV, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 60, 70));

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Export staff list");
        ExportStaff.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 80, 30));

        ExportPackage.setBackground(new java.awt.Color(94, 91, 91));
        ExportPackage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExportPackageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExportPackageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExportPackageMouseExited(evt);
            }
        });
        ExportPackage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Export package list");
        ExportPackage.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 110, 30));

        btnThemHV5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/icons8_microsoft_excel_60px_1.png"))); // NOI18N
        ExportPackage.add(btnThemHV5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 60, 70));

        ExportVoucher.setBackground(new java.awt.Color(94, 91, 91));
        ExportVoucher.setPreferredSize(new java.awt.Dimension(120, 120));
        ExportVoucher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExportVoucherMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExportVoucherMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExportVoucherMouseExited(evt);
            }
        });
        ExportVoucher.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Export bill list");
        ExportVoucher.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 70, 30));

        btnThemHV6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/icons8_microsoft_excel_60px_1.png"))); // NOI18N
        ExportVoucher.add(btnThemHV6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 60, 70));

        ExportBill.setBackground(new java.awt.Color(94, 91, 91));
        ExportBill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExportBillMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExportBillMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExportBillMouseExited(evt);
            }
        });
        ExportBill.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Export voucher list");
        ExportBill.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 100, 30));

        btnThemHV2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/icons8_microsoft_excel_60px_1.png"))); // NOI18N
        ExportBill.add(btnThemHV2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 60, 70));

        ExportDetailBill.setBackground(new java.awt.Color(94, 91, 91));
        ExportDetailBill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExportDetailBillMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExportDetailBillMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExportDetailBillMouseExited(evt);
            }
        });
        ExportDetailBill.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Export bill detail list");
        ExportDetailBill.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 100, 30));

        btnThemHV4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/icons8_microsoft_excel_60px_1.png"))); // NOI18N
        ExportDetailBill.add(btnThemHV4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, 70));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/3588731.jpg.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 540, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ExportBill, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExportCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ExportVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExportStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ExportDetailBill, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExportPackage, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ExportCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExportStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExportPackage, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ExportBill, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExportVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExportDetailBill, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ExportCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExportCustomerMouseClicked
        ee.ExportCustomer();
    }//GEN-LAST:event_ExportCustomerMouseClicked

    private void ExportCustomerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExportCustomerMouseEntered
        ExportCustomer.setBackground(Color.decode("#565255"));
    }//GEN-LAST:event_ExportCustomerMouseEntered

    private void ExportCustomerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExportCustomerMouseExited

        ExportCustomer.setBackground(Color.decode("#5E5B5B"));
    }//GEN-LAST:event_ExportCustomerMouseExited

    private void ExportStaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExportStaffMouseClicked
       ee.ExportStaff();
    }//GEN-LAST:event_ExportStaffMouseClicked

    private void ExportStaffMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExportStaffMouseEntered
        ExportStaff.setBackground(Color.decode("#565255"));
    }//GEN-LAST:event_ExportStaffMouseEntered

    private void ExportStaffMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExportStaffMouseExited
        ExportStaff.setBackground(Color.decode("#5E5B5B"));
    }//GEN-LAST:event_ExportStaffMouseExited

    private void ExportPackageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExportPackageMouseClicked
        ee.ExportPackage();
    }//GEN-LAST:event_ExportPackageMouseClicked

    private void ExportPackageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExportPackageMouseEntered
        ExportPackage.setBackground(Color.decode("#565255"));
    }//GEN-LAST:event_ExportPackageMouseEntered

    private void ExportPackageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExportPackageMouseExited
        ExportPackage.setBackground(Color.decode("#5E5B5B"));
    }//GEN-LAST:event_ExportPackageMouseExited

    private void ExportVoucherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExportVoucherMouseClicked
        ee.ExportVoucher();
    }//GEN-LAST:event_ExportVoucherMouseClicked

    private void ExportVoucherMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExportVoucherMouseEntered
        ExportVoucher.setBackground(Color.decode("#565255"));
    }//GEN-LAST:event_ExportVoucherMouseEntered

    private void ExportVoucherMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExportVoucherMouseExited
        ExportVoucher.setBackground(Color.decode("#5E5B5B"));
    }//GEN-LAST:event_ExportVoucherMouseExited

    private void ExportBillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExportBillMouseClicked
        ee.ExportBill();
    }//GEN-LAST:event_ExportBillMouseClicked

    private void ExportBillMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExportBillMouseEntered
        ExportBill.setBackground(Color.decode("#565255"));
    }//GEN-LAST:event_ExportBillMouseEntered

    private void ExportBillMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExportBillMouseExited
        ExportBill.setBackground(Color.decode("#5E5B5B"));
    }//GEN-LAST:event_ExportBillMouseExited

    private void ExportDetailBillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExportDetailBillMouseClicked
        ee.ExportBillDetail();
    }//GEN-LAST:event_ExportDetailBillMouseClicked

    private void ExportDetailBillMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExportDetailBillMouseEntered

        ExportDetailBill.setBackground(Color.decode("#565255"));
    }//GEN-LAST:event_ExportDetailBillMouseEntered

    private void ExportDetailBillMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExportDetailBillMouseExited
        ExportDetailBill.setBackground(Color.decode("#5E5B5B"));
    }//GEN-LAST:event_ExportDetailBillMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ExportBill;
    private javax.swing.JPanel ExportCustomer;
    private javax.swing.JPanel ExportDetailBill;
    private javax.swing.JPanel ExportPackage;
    private javax.swing.JPanel ExportStaff;
    private javax.swing.JPanel ExportVoucher;
    private javax.swing.JLabel btnThemHV;
    private javax.swing.JLabel btnThemHV1;
    private javax.swing.JLabel btnThemHV2;
    private javax.swing.JLabel btnThemHV4;
    private javax.swing.JLabel btnThemHV5;
    private javax.swing.JLabel btnThemHV6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
