/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Admin;

import Controller.ChiTietHoaDonCTR;
import Controller.GoiTapCTR;
import Controller.HoaDonCTR;
import Controller.HoiVienCTR;
import Controller.LoaiGoiTapCTR;
import Controller.NhanVienCTR;
import Controller.VeTapCTR;
import Object.ChiTietHoaDon;
import Object.HoaDon;
import Processor.NumberProcesser;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Admin
 */
public class JPanelBills extends javax.swing.JPanel {

    HoaDonCTR hdc = new HoaDonCTR();
    VeTapCTR vtc = new VeTapCTR();
    DefaultTableModel dTable = new DefaultTableModel();
    DefaultTableModel dTable1 = new DefaultTableModel();
    NumberProcesser np = new NumberProcesser();
    HoiVienCTR hvctr = new HoiVienCTR();
    ArrayList<HoaDon> lhd = new ArrayList();
    ChiTietHoaDonCTR cthdc = new ChiTietHoaDonCTR();
    ArrayList<ChiTietHoaDon> listCTHD = new ArrayList<>();
    GoiTapCTR gtc = new GoiTapCTR();
    LoaiGoiTapCTR lgtc = new LoaiGoiTapCTR();

    private int MaHD;

    public JPanelBills() {
        initComponents();
        dTable = (DefaultTableModel) tableHoaDon.getModel();
        dTable1 = (DefaultTableModel) tableCTHD.getModel();
        lhd = hdc.getData();
        showAllDataHD();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableHoaDon = new javax.swing.JTable();
        txtToTalDue = new javax.swing.JLabel();
        txtStaffID = new javax.swing.JLabel();
        txtInvoiceDate = new javax.swing.JLabel();
        txtInvoiceNo = new javax.swing.JLabel();
        txtEmail = new javax.swing.JLabel();
        txtTel = new javax.swing.JLabel();
        txtCustomerID = new javax.swing.JLabel();
        txtCustomerName = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCTHD = new javax.swing.JTable();
        BackGround = new javax.swing.JLabel();
        txtSearchInput = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableHoaDon.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        tableHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Bill ID", "Date", "Customer", "Staff ID", "Total Price"
            }
        ));
        tableHoaDon.setGridColor(new java.awt.Color(255, 255, 255));
        tableHoaDon.setPreferredSize(new java.awt.Dimension(375, 500));
        tableHoaDon.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableHoaDon.setShowGrid(false);
        tableHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableHoaDonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableHoaDon);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 920, 530));

        txtToTalDue.setFont(new java.awt.Font("Segoe UI Light", 0, 8)); // NOI18N
        txtToTalDue.setText("null");
        jPanel1.add(txtToTalDue, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 155, -1, -1));

        txtStaffID.setFont(new java.awt.Font("Segoe UI Light", 0, 8)); // NOI18N
        txtStaffID.setText("null");
        jPanel1.add(txtStaffID, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 145, -1, -1));

        txtInvoiceDate.setFont(new java.awt.Font("Segoe UI Light", 0, 8)); // NOI18N
        txtInvoiceDate.setText("null");
        jPanel1.add(txtInvoiceDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 130, -1, -1));

        txtInvoiceNo.setFont(new java.awt.Font("Segoe UI Light", 0, 8)); // NOI18N
        txtInvoiceNo.setText("null");
        jPanel1.add(txtInvoiceNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 120, -1, -1));

        txtEmail.setFont(new java.awt.Font("Segoe UI Light", 0, 8)); // NOI18N
        txtEmail.setText("null");
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 152, -1, -1));

        txtTel.setFont(new java.awt.Font("Segoe UI Light", 0, 8)); // NOI18N
        txtTel.setText("null");
        jPanel1.add(txtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 140, -1, -1));

        txtCustomerID.setFont(new java.awt.Font("Segoe UI Light", 0, 8)); // NOI18N
        txtCustomerID.setText("null");
        jPanel1.add(txtCustomerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 120, -1, -1));

        txtCustomerName.setFont(new java.awt.Font("Segoe UI Light", 0, 8)); // NOI18N
        txtCustomerName.setText("null");
        jPanel1.add(txtCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 130, -1, -1));

        tableCTHD.setFont(new java.awt.Font("Segoe UI Light", 0, 8)); // NOI18N
        tableCTHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Package name", "Package type", "Start date", "End date", "Voucher", "Price"
            }
        ));
        tableCTHD.setPreferredSize(new java.awt.Dimension(450, 303));
        tableCTHD.setShowHorizontalLines(false);
        tableCTHD.setShowVerticalLines(false);
        jScrollPane2.setViewportView(tableCTHD);
        JTableHeader header = tableCTHD.getTableHeader();
        header.setFont(new Font("Segoe UI Light",Font.PLAIN,9));
        header.setBackground(Color.LIGHT_GRAY);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 180, 390, 330));

        BackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/Invoice874x1240.jpg"))); // NOI18N
        jPanel1.add(BackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, -1, -1));

        txtSearchInput.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        txtSearchInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchInputActionPerformed(evt);
            }
        });
        txtSearchInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchInputKeyReleased(evt);
            }
        });
        jPanel1.add(txtSearchInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 143, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/icons8_search_30px.png"))); // NOI18N
        jLabel1.setText("Nhập thông tin:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 30, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableHoaDonMouseClicked
        // TODO add your handling code here:
        int rowSelected = tableHoaDon.getSelectedRow();
        if (rowSelected != -1) {
            int index = Integer.parseInt(tableHoaDon.getValueAt(rowSelected, 0) + "") - 1;
            MaHD = lhd.get(index).getMaHD();
            txtInvoiceNo.setText(MaHD + "");
            txtStaffID.setText(hdc.getDataByMaHD(MaHD).getMaNV() + "");
            txtInvoiceDate.setText(hdc.getDataByMaHD(MaHD).getNgayLap());
            txtCustomerID.setText(hdc.getDataByMaHD(MaHD).getMaHV() + "");
            txtCustomerName.setText(hvctr.getData(hdc.getDataByMaHD(MaHD).getMaHV()).getTenHV() + "");
            txtToTalDue.setText(np.FloatToVND(hdc.getPriceByMaHD(MaHD)));
            txtTel.setText(hvctr.getData(hdc.getDataByMaHD(MaHD).getMaHV()).getSDT() + "");
            listCTHD = cthdc.getDataByMaHD(MaHD);
            dTable1 = (DefaultTableModel) tableCTHD.getModel();
            showData();
        }


    }//GEN-LAST:event_tableHoaDonMouseClicked

    private void showData() {
        if (tableCTHD.getRowCount() > 0) {
            dTable1.setRowCount(0); // reset nd trong bang ve 0
        }
        for (ChiTietHoaDon c : listCTHD) {
            dTable1.addRow(new Object[]{gtc.getData(c.getMaGoiTap()).getTenGoiTap(), lgtc.getTenLoaiGoiTap(c.getMaLoaiGoiTap()), c.getNgayBatDau(), c.getNgayKetThuc(), c.getMaVoucher(), c.getGiaCuoi()});

        }
    }
    private void txtSearchInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchInputActionPerformed

    private void txtSearchInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchInputKeyReleased
        // TODO add your handling code here:
        DefaultTableModel table = (DefaultTableModel) tableHoaDon.getModel();
        TableRowSorter<DefaultTableModel> rowSorter = new TableRowSorter<DefaultTableModel>(table);
        String search = txtSearchInput.getText();
        if (search.trim().length() == 0) {
            rowSorter.setRowFilter(null);
        } else {
            rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + search));
        }
        tableHoaDon.setRowSorter(rowSorter);
    }//GEN-LAST:event_txtSearchInputKeyReleased

    public void showAllDataHD() {
        lhd = hdc.getData();
        int stt = 0;
        float TC = 0f;
        if (tableHoaDon.getRowCount() > 0) {
            dTable.setRowCount(0); // reset nd trong bang ve 0
        }
        ArrayList<HoaDon> listHD = new ArrayList<>();
        listHD = hdc.getData();
        NhanVienCTR nvc = new NhanVienCTR();
        for (HoaDon hoaDon : listHD) {
            dTable.addRow(new Object[]{++stt, hoaDon.getMaHD(), hoaDon.getNgayLap(),
                hvctr.getData(hoaDon.getMaHV()).getTenHV(), hoaDon.getMaNV(),
                np.FloatToVND(hdc.getPriceByMaHD(hoaDon.getMaHD()))});
            TC += hdc.getPriceByMaHD(hoaDon.getMaHD());

        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackGround;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableCTHD;
    private javax.swing.JTable tableHoaDon;
    private javax.swing.JLabel txtCustomerID;
    private javax.swing.JLabel txtCustomerName;
    private javax.swing.JLabel txtEmail;
    private javax.swing.JLabel txtInvoiceDate;
    private javax.swing.JLabel txtInvoiceNo;
    private javax.swing.JTextField txtSearchInput;
    private javax.swing.JLabel txtStaffID;
    private javax.swing.JLabel txtTel;
    private javax.swing.JLabel txtToTalDue;
    // End of variables declaration//GEN-END:variables
}
