/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Staff;

import Controller.HoiVienCTR;
import Object.HoiVien;
import Processor.DateProcessor;
import Processor.ImageScaler;
import java.io.File;
import java.util.ArrayList;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
//import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import Processor.Regex;
import View.Dialog.ErrorDialog;
import View.Dialog.SuccessDialog;

/**
 *
 * @author Admin
 */
public class CustomerRegistrationForm extends javax.swing.JFrame {

    HoiVienCTR hvc = new HoiVienCTR();
    ArrayList<HoiVien> lhv = new ArrayList();
    DefaultTableModel Dtable;
    String imageURL = "C:\\Users\\Admin\\Documents\\NetBeansProjects\\DoAnQuanLyGYM\\src\\View\\Image\\defaultAVT.jpg";
    Boolean addable = true;

    public CustomerRegistrationForm() {

        initComponents();
        this.setLocationRelativeTo(null);
        ImageScaler is = new ImageScaler();
        Image.setIcon(is.ImageScaler(imageURL, 128, 128));
        Dtable = (DefaultTableModel) tableHV.getModel();
        showHV();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableHV = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btnThemHV = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnClear = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        monthComboBox = new javax.swing.JComboBox<>();
        txtCMND = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtFaceBook = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        comboboxGioiTinh = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        btnUpLoad = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        dateComboBox = new javax.swing.JComboBox<>();
        txtTenHV = new javax.swing.JTextField();
        Image = new javax.swing.JLabel();
        txtYear = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableHV.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        tableHV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Customer ID", "Customer name", "Date of Birth", "Address", "Phone", "Email", "Sex", "Facebook", "ID card"
            }
        ));
        tableHV.setPreferredSize(new java.awt.Dimension(180, 615));
        tableHV.setShowGrid(false);
        tableHV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableHVMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tableHV);

        jPanel3.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 631));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        btnThemHV.setToolTipText("Thêm hội viên");
        btnThemHV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/icons8_add_user_group_man_man_48px.png"))); // NOI18N
        btnThemHV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemHVMouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel13.setText("Add Customer");

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/icons8_broom_48px.png"))); // NOI18N
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel14.setText("Clear");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(198, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnThemHV, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel13))
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(115, 115, 115))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnThemHV, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(787, 378, -1, -1));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel15.setText("Phone (*):");

        jLabel16.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel16.setText("Image");

        monthComboBox.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        monthComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        txtCMND.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        txtCMND.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        txtEmail.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        txtEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        txtDiaChi.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        txtDiaChi.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        jLabel17.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel17.setText("Email:");

        jLabel18.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel18.setText("Address:");

        jLabel19.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel19.setText("Sex:");

        txtFaceBook.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        txtFaceBook.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        jLabel20.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel20.setText("Date of birth:");

        comboboxGioiTinh.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        comboboxGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        jLabel21.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel21.setText("Facebook:");

        btnUpLoad.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        btnUpLoad.setText("Browse");
        btnUpLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpLoadActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel22.setText("Full name(*):");

        txtSDT.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        txtSDT.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        jLabel23.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel23.setText("ID card (*):");

        dateComboBox.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        dateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        dateComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateComboBoxActionPerformed(evt);
            }
        });

        txtTenHV.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        txtTenHV.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        txtYear.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        txtYear.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Image, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(19, 19, 19))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel23)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenHV, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFaceBook, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(83, 83, 83)
                                .addComponent(btnUpLoad))
                            .addComponent(comboboxGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(62, 62, 62))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel18)
                                .addComponent(jLabel20)
                                .addComponent(jLabel15)
                                .addComponent(jLabel17))
                            .addGap(28, 28, 28)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(dateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(33, 33, 33)
                                    .addComponent(monthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel22))
                    .addContainerGap(219, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTenHV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Image, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboboxGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(btnUpLoad)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel23)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtFaceBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel21))
                                .addGap(18, 18, 18)
                                .addComponent(txtCMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31))))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(jLabel22)
                    .addGap(15, 15, 15)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(monthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel20))
                    .addGap(24, 24, 24)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(jLabel17)
                    .addContainerGap(155, Short.MAX_VALUE)))
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(787, 24, -1, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1370, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableHVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableHVMouseClicked
        // TODO add your handling code here:
        addable = false;
        btnThemHV.setEnabled(false);
        ImageScaler is = new ImageScaler();
        int index = tableHV.getSelectedRow();
        Image.setIcon(is.ImageScaler(lhv.get(index).getAnh(), 128, 128));
        txtTenHV.setText(lhv.get(index).getTenHV());
        txtDiaChi.setText(lhv.get(index).getDiaChi());
        txtEmail.setText(lhv.get(index).getEmail());
        txtCMND.setText(lhv.get(index).getCMND());
        txtFaceBook.setText(lhv.get(index).getFaceBook());
        txtSDT.setText(lhv.get(index).getSDT());
        comboboxGioiTinh.setEnabled(false);
        String ngaySinh = lhv.get(index).getNgaySinh();
        dateComboBox.setSelectedIndex(Integer.parseInt(ngaySinh.split("-")[2]) - 1);
        monthComboBox.setSelectedIndex(Integer.parseInt(ngaySinh.split("-")[1]) - 1);
        txtYear.setText(ngaySinh.split("-")[0]);

    }//GEN-LAST:event_tableHVMouseClicked

    private void btnThemHVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemHVMouseClicked
        if (addable == true) {
            Boolean SDTCheck = true;
            Boolean TenHVCheck = true;
            Boolean CMNDCheck = true;
            Boolean EmailCheck = true;
            Boolean FacebookCheck = true;
            Boolean DiaChiCheck = true;
            Boolean IsOK = true;
            String TenHV = txtTenHV.getText();//khong duoc rong
            try {
                Integer.parseInt(txtYear.getText() + "");
                String DiaChi = txtDiaChi.getText();
                String Email = txtEmail.getText();
                String NgaySinh = (dateComboBox.getSelectedItem() + "/" + monthComboBox.getSelectedItem() + "/" + txtYear.getText());
                String SDT = txtSDT.getText();
                String GioiTinh = comboboxGioiTinh.getSelectedItem().toString();
                String FaceBook = txtFaceBook.getText();
                String CMND = txtCMND.getText();
                String Anh = imageURL;
                DateProcessor dp = new DateProcessor();
                if (dp.isDate(NgaySinh) == false) {
                    new ErrorDialog("Invalid date of birth!").setVisible(true);
                } else {
                    if (TenHV.isEmpty() || SDT.isEmpty() || CMND.isEmpty()) {
                        new ErrorDialog("Please fill all the field which have (*)").setVisible(true);
                        IsOK = false;
                    } else {
                        Pattern pattern = Pattern.compile(Regex.TenPattern);

                        if (!pattern.matcher(txtTenHV.getText()).find()) {
                            IsOK = false;
                            TenHVCheck = false;
                        }

                        pattern = Pattern.compile(Regex.SdtPattern);

                        if (!pattern.matcher(txtSDT.getText()).find()) {
                            IsOK = false;
                            SDTCheck = false;
                        }
                        pattern = Pattern.compile(Regex.CMNDPattern);

                        if (!pattern.matcher(txtCMND.getText()).find()) {
                            IsOK = false;
                            CMNDCheck = false;
                        }                   
                        if (!txtEmail.getText().equals("")) {
                            pattern = Pattern.compile(Regex.EmailPattern);
                            if (!pattern.matcher(txtEmail.getText()).find()) {
                                IsOK = false;
                                EmailCheck = false;
                            }
                        }
                        if (!txtDiaChi.getText().equals("")) {
                            pattern = Pattern.compile(Regex.DiaChiPattern);
                            if (!pattern.matcher(txtDiaChi.getText()).find()) {
                                IsOK = false;
                                DiaChiCheck = false;
                            }
                        }
                        if (!txtFaceBook.getText().equals("")) {
                            pattern = Pattern.compile(Regex.TenPattern);
                            if (!pattern.matcher(txtFaceBook.getText()).find()) {
                                IsOK = false;
                                FacebookCheck = false;
                            }
                        }
                        if (TenHVCheck == false || EmailCheck == false || SDTCheck == false || CMNDCheck == false || FacebookCheck == false || DiaChiCheck == false) {
                            new ErrorDialog("Please type match regex!").setVisible(true);
                        }
                    }
                    if (IsOK) {
                        HoiVien hv = new HoiVien(0, TenHV, dp.ReverseDate(NgaySinh), DiaChi, SDT, Email, GioiTinh, FaceBook, Anh, CMND);
                        if (hvc.AddData(hv)) {
                            new SuccessDialog("Add successfully!").setVisible(true);
                            showHV();
                        } else {
                            new ErrorDialog("ID card has been already exist!").setVisible(true);
                        }
                    }
                }
            } catch (Exception e) {
                new ErrorDialog("Invalid year input!").setVisible(true);
            }
        }

    }//GEN-LAST:event_btnThemHVMouseClicked

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked

        addable = true;
        btnThemHV.setEnabled(true);
        txtTenHV.setText("");
        txtDiaChi.setText("");
        dateComboBox.setSelectedItem("1");
        monthComboBox.setSelectedItem("1");
        txtYear.setText("2000");
        txtSDT.setText("");
        txtEmail.setText("");
        txtFaceBook.setText("");
        txtCMND.setText("");
        comboboxGioiTinh.setSelectedItem("Nam");
        comboboxGioiTinh.setEnabled(true);
    }//GEN-LAST:event_btnClearMouseClicked

    private void btnUpLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpLoadActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter imageFilter = new FileNameExtensionFilter("Image", "jpg", "png");
        fileChooser.setFileFilter(imageFilter);
        fileChooser.setMultiSelectionEnabled(false);
        int x = fileChooser.showDialog(this, "Choose");
        if (x == JFileChooser.APPROVE_OPTION) {
            ImageScaler is = new ImageScaler();
            File f = fileChooser.getSelectedFile();
            Image.setIcon(is.ImageScaler(f.getPath(), 128, 128));
            imageURL = f.getAbsolutePath();
            //System.out.println(imageURL);
        }
    }//GEN-LAST:event_btnUpLoadActionPerformed

    private void dateComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateComboBoxActionPerformed

    public void showHV() {
        lhv = hvc.getData();
        if (tableHV.getRowCount() > 0) {
            Dtable.setRowCount(0);
        }
        for (HoiVien hoiVien : lhv) {
            Dtable.addRow(hoiVien.toArray());
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Image;
    private javax.swing.JLabel btnClear;
    private javax.swing.JLabel btnThemHV;
    private javax.swing.JButton btnUpLoad;
    private javax.swing.JComboBox<String> comboboxGioiTinh;
    private javax.swing.JComboBox<String> dateComboBox;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JComboBox<String> monthComboBox;
    private javax.swing.JTable tableHV;
    private javax.swing.JTextField txtCMND;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFaceBook;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenHV;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
