/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Staff;

import Controller.HoiVienCTR;
import View.LoginAndForgetPassword.LoginForm;
import Controller.TaiKhoanCTR;
import Object.HoiVien;
import View.Dialog.ErrorDialog;
import View.Dialog.WarningDialg;
import View.Dialog.WarningExitDialog;
import java.awt.Color;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
//import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class StaffForm extends javax.swing.JFrame {

    /**
     * Creates new form FormNV1
     */
    String MaNV = "";
    TaiKhoanCTR tkc = new TaiKhoanCTR();

    public StaffForm() {
        initComponents();
    }

    public StaffForm(String TenDN) {
        initComponents();
        this.setTitle("GymMasterV1.0");
        this.setLocationRelativeTo(null);
        txtUser.setText(TenDN);
        MaNV = TenDN;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnDoiMK = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        CustomerReg = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnThemHV = new javax.swing.JLabel();
        PackageReg = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnDangKiGoiTap = new javax.swing.JLabel();
        PackageExtension = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnGiaHanGoiTap = new javax.swing.JLabel();
        CheckCustomer = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btnDiemDanh = new javax.swing.JLabel();
        SellTicket = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnVeTap = new javax.swing.JLabel();
        PackageList = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnDanhSachGoiTap = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtUser = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setOpacity(0.0F);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(42, 39, 41));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDoiMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/icons8_manager_36px.png"))); // NOI18N
        btnDoiMK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDoiMKMouseClicked(evt);
            }
        });
        jPanel1.add(btnDoiMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 62, -1, -1));

        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/icons8_exit_36px.png"))); // NOI18N
        btnLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogOutMouseClicked(evt);
            }
        });
        jPanel1.add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 116, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 50, 790));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CustomerReg.setBackground(new java.awt.Color(94, 91, 91));
        CustomerReg.setPreferredSize(new java.awt.Dimension(120, 120));
        CustomerReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomerRegMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CustomerRegMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CustomerRegMouseExited(evt);
            }
        });
        CustomerReg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Customer Register");
        CustomerReg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 100, 30));

        btnThemHV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/icons8_add_male_user_80px.png"))); // NOI18N
        CustomerReg.add(btnThemHV, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 80, 80));

        jPanel2.add(CustomerReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 200, 200));

        PackageReg.setBackground(new java.awt.Color(94, 91, 91));
        PackageReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PackageRegMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PackageRegMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PackageRegMouseExited(evt);
            }
        });
        PackageReg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Package register");
        PackageReg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 100, 30));

        btnDangKiGoiTap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/icons8_Add_to_Collection_80px.png"))); // NOI18N
        PackageReg.add(btnDangKiGoiTap, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 80, 80));

        jPanel2.add(PackageReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 200, 200));

        PackageExtension.setBackground(new java.awt.Color(94, 91, 91));
        PackageExtension.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PackageExtensionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PackageExtensionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PackageExtensionMouseExited(evt);
            }
        });
        PackageExtension.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Package extension");
        PackageExtension.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 100, 30));

        btnGiaHanGoiTap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/icons8_Product_Management_80px.png"))); // NOI18N
        PackageExtension.add(btnGiaHanGoiTap, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 80, 80));

        jPanel2.add(PackageExtension, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 200, 200));

        CheckCustomer.setBackground(new java.awt.Color(94, 91, 91));
        CheckCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CheckCustomerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CheckCustomerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CheckCustomerMouseExited(evt);
            }
        });
        CheckCustomer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Check customer info");
        CheckCustomer.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 100, 30));

        btnDiemDanh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/icons8_checked_user_female_80px.png"))); // NOI18N
        CheckCustomer.add(btnDiemDanh, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 80, 80));

        jPanel2.add(CheckCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 200, 200));

        SellTicket.setBackground(new java.awt.Color(94, 91, 91));
        SellTicket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SellTicketMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SellTicketMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SellTicketMouseExited(evt);
            }
        });
        SellTicket.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Sell ticket");
        SellTicket.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 60, 30));

        btnVeTap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/icons8_passport_and_tickets_80px.png"))); // NOI18N
        SellTicket.add(btnVeTap, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 80, 80));

        jPanel2.add(SellTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 200, 200));

        PackageList.setBackground(new java.awt.Color(94, 91, 91));
        PackageList.setPreferredSize(new java.awt.Dimension(120, 120));
        PackageList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PackageListMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PackageListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PackageListMouseExited(evt);
            }
        });
        PackageList.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Package list");
        PackageList.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 70, 30));

        btnDanhSachGoiTap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/icons8_bulleted_list_80px.png"))); // NOI18N
        PackageList.add(btnDanhSachGoiTap, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 80, 80));

        jPanel2.add(PackageList, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 200, 200));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 820, 620));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 10)); // NOI18N
        jLabel1.setText("N18DCCN032@student.ptitHCM.edu.vn");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 180, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 60)); // NOI18N
        jLabel2.setText("GymMaster V1.1");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 430, 90));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 1300, 170));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUser.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        txtUser.setText("User");
        jPanel4.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 0, -1, 30));

        jLabel38.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("X");
        jLabel38.setPreferredSize(new java.awt.Dimension(25, 25));
        jLabel38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel38MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 0, 30, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/3588731.jpg.png"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 200, 480, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogOutMouseClicked
        // TODO add your handling code here:
        if (tkc.getData(MaNV).getLoaiTK() == 1)
            this.setVisible(false);
        else {
            LoginForm f = new LoginForm();
            f.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnLogOutMouseClicked

    private void btnDoiMKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoiMKMouseClicked
        // TODO add your handling code here:
        //ChangeDetailForm f = new ChangeDetailForm(MaNV);
        //f.setVisible(true);
        new ChangDetailDialog(this, true, MaNV).setVisible(true);

    }//GEN-LAST:event_btnDoiMKMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for (double i = 0.0; i <= 1; i += 0.1) {
            String val = i + "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try {
                Thread.sleep(50);
            } catch (InterruptedException ex) {
                Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void CustomerRegMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerRegMouseEntered
        CustomerReg.setBackground(Color.decode("#565255"));
    }//GEN-LAST:event_CustomerRegMouseEntered

    private void CustomerRegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerRegMouseClicked
        CustomerRegistrationForm FDKHV = new CustomerRegistrationForm();
        FDKHV.setVisible(true);
    }//GEN-LAST:event_CustomerRegMouseClicked

    private void PackageRegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PackageRegMouseClicked
        ArrayList<HoiVien> list = new ArrayList();
        HoiVienCTR hvc = new HoiVienCTR();
        list = hvc.getData();
        if (list.isEmpty()) {
            new ErrorDialog("No customer availble!").setVisible(true);
        } else {
            ChooseCustomerForm fchv = new ChooseCustomerForm(true, MaNV);
            fchv.setVisible(true);
        }

    }//GEN-LAST:event_PackageRegMouseClicked

    private void PackageExtensionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PackageExtensionMouseClicked
        ArrayList<HoiVien> list = new ArrayList();
        HoiVienCTR hvc = new HoiVienCTR();
        list = hvc.getData();
        if (list.isEmpty()) {
            new ErrorDialog("No customer availble! ").setVisible(true);
        } else {
            ChooseCustomerForm fchv = new ChooseCustomerForm(false, MaNV);
            fchv.setVisible(true);
        }
    }//GEN-LAST:event_PackageExtensionMouseClicked

    private void SellTicketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SellTicketMouseClicked
        new TicketForm(this, true, MaNV).setVisible(true);
    }//GEN-LAST:event_SellTicketMouseClicked

    private void PackageListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PackageListMouseClicked
        new PackageListDialog(this, true).setVisible(true);
    }//GEN-LAST:event_PackageListMouseClicked

    private void CheckCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckCustomerMouseClicked
        new CheckInfoDialog(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_CheckCustomerMouseClicked

    private void PackageRegMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PackageRegMouseEntered
        PackageReg.setBackground(Color.decode("#565255"));
    }//GEN-LAST:event_PackageRegMouseEntered

    private void PackageExtensionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PackageExtensionMouseEntered
       PackageExtension.setBackground(Color.decode("#565255"));
    }//GEN-LAST:event_PackageExtensionMouseEntered

    private void SellTicketMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SellTicketMouseEntered
        SellTicket.setBackground(Color.decode("#565255"));
    }//GEN-LAST:event_SellTicketMouseEntered

    private void PackageListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PackageListMouseEntered
        PackageList.setBackground(Color.decode("#565255"));
    }//GEN-LAST:event_PackageListMouseEntered

    private void CheckCustomerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckCustomerMouseEntered

        CheckCustomer.setBackground(Color.decode("#565255"));
    }//GEN-LAST:event_CheckCustomerMouseEntered

    private void CustomerRegMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerRegMouseExited
 
        CustomerReg.setBackground(Color.decode("#5E5B5B"));
    }//GEN-LAST:event_CustomerRegMouseExited

    private void PackageRegMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PackageRegMouseExited
        PackageReg.setBackground(Color.decode("#5E5B5B"));
    }//GEN-LAST:event_PackageRegMouseExited

    private void PackageExtensionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PackageExtensionMouseExited
        PackageExtension.setBackground(Color.decode("#5E5B5B"));
    }//GEN-LAST:event_PackageExtensionMouseExited

    private void SellTicketMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SellTicketMouseExited
        SellTicket.setBackground(Color.decode("#5E5B5B"));
    }//GEN-LAST:event_SellTicketMouseExited

    private void PackageListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PackageListMouseExited
        PackageList.setBackground(Color.decode("#5E5B5B"));
    }//GEN-LAST:event_PackageListMouseExited

    private void CheckCustomerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckCustomerMouseExited
        CheckCustomer.setBackground(Color.decode("#5E5B5B"));
    }//GEN-LAST:event_CheckCustomerMouseExited

    private void jLabel38MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel38MouseClicked
        // TODO add your handling code here:
        WarningExitDialog w = new WarningExitDialog("Are you sure to exit the program?");
        w.setVisible(true);
        if (w.Accept == true)
            System.exit(0);
    }//GEN-LAST:event_jLabel38MouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CheckCustomer;
    private javax.swing.JPanel CustomerReg;
    private javax.swing.JPanel PackageExtension;
    private javax.swing.JPanel PackageList;
    private javax.swing.JPanel PackageReg;
    private javax.swing.JPanel SellTicket;
    private javax.swing.JLabel btnDangKiGoiTap;
    private javax.swing.JLabel btnDanhSachGoiTap;
    private javax.swing.JLabel btnDiemDanh;
    private javax.swing.JLabel btnDoiMK;
    private javax.swing.JLabel btnGiaHanGoiTap;
    private javax.swing.JLabel btnLogOut;
    private javax.swing.JLabel btnThemHV;
    private javax.swing.JLabel btnVeTap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel txtUser;
    // End of variables declaration//GEN-END:variables
}
