/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Staff;

import Controller.GoiTapHoanChinhCTR;
import Controller.GoiTapCTR;
import Controller.LoaiGoiTapCTR;
import Controller.VeTapCTR;
import Object.VeTap;
import Processor.DateProcessor;
import View.Dialog.SuccessDialog;
import java.util.ArrayList;
//import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class TicketForm extends javax.swing.JDialog {

    /**
     * Creates new form TicketForm
     */
    GoiTapCTR gtc = new GoiTapCTR();
    GoiTapHoanChinhCTR ctgtc = new GoiTapHoanChinhCTR();
    LoaiGoiTapCTR lgtc = new LoaiGoiTapCTR();
    VeTapCTR vtc = new VeTapCTR();
    DateProcessor dp = new DateProcessor();
    int MaGoiTap = 1;
    int MaLoaiGoiTap = 1;
    Float ThanhTien = 0f;

    public TicketForm(java.awt.Frame parent, boolean modal) {
        initComponents();
        //txtNV.setText(MaNV); 
    }

    public TicketForm(java.awt.Frame parent, boolean modal, String MaNV) {
        initComponents();
        this.setTitle("Ticket seller");
        this.setLocationRelativeTo(null);
        //this.setIconImage(image);
        txtNV.setText(MaNV);
        int Ngay = java.time.LocalDate.now().getDayOfMonth();
        int Thang = java.time.LocalDate.now().getMonthValue();
        int Nam = java.time.LocalDate.now().getYear();
        String NgayLapHD = Ngay + "/" + Thang + "/" + Nam;
        txtNgayLap.setText(NgayLapHD);
        ArrayList<String> list1 = gtc.ToString();
        for (String string : list1) {
            GoiTapComboBox.addItem(string);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        GoiTapComboBox = new javax.swing.JComboBox<>();
        txtDonGia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNV = new javax.swing.JLabel();
        txtNgayLap = new javax.swing.JLabel();
        btnInVe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel2.setText("Package:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        GoiTapComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoiTapComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(GoiTapComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 170, -1));

        txtDonGia.setEditable(false);
        txtDonGia.setBackground(new java.awt.Color(255, 255, 255));
        txtDonGia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDonGia.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txtDonGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDonGiaActionPerformed(evt);
            }
        });
        jPanel1.add(txtDonGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 110, 170, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel6.setText("Price");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel9.setText("Staff");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel3.setText("Date");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        txtNV.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jPanel1.add(txtNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 127, 23));

        txtNgayLap.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jPanel1.add(txtNgayLap, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 130, 20));

        btnInVe.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        btnInVe.setText("Print");
        btnInVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInVeActionPerformed(evt);
            }
        });
        jPanel1.add(btnInVe, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GoiTapComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoiTapComboBoxActionPerformed

        MaGoiTap = gtc.getMaGoiTap(GoiTapComboBox.getSelectedItem() + "");
        txtDonGia.setText(ctgtc.findPrice(MaGoiTap, 10000) + "");

    }//GEN-LAST:event_GoiTapComboBoxActionPerformed

    private void txtDonGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDonGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDonGiaActionPerformed

    private void btnInVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInVeActionPerformed
        // TODO add your handling code here:
        int MaGoiTap = gtc.getMaGoiTap(GoiTapComboBox.getSelectedItem() + "");
        float Gia = Float.parseFloat(txtDonGia.getText());
        String NgayLap = txtNgayLap.getText();
        VeTap vt = new VeTap(10000, dp.ReverseDate(NgayLap), MaGoiTap, 10000, Gia);
        vtc.AddData(vt);
        new SuccessDialog("Printed!").setVisible(true);
    }//GEN-LAST:event_btnInVeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> GoiTapComboBox;
    private javax.swing.JButton btnInVe;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JLabel txtNV;
    private javax.swing.JLabel txtNgayLap;
    // End of variables declaration//GEN-END:variables
}
